name: launch_at_startup_example
description: launch_at_startup through its 0.5.x compatible API.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  launch_at_startup:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.7

msix_config:
  display_name: launch_at_startup_example
  publisher_display_name: LeanFlutter
  identity_name: dev.leanflutter.examples.launchatstartupexample
  msix_version: 1.0.0.0
