name: launch_at_startup
description: This plugin allows Flutter desktop apps to Auto launch on startup / login.
version: 0.6.0
homepage: https://github.com/leanflutter/launch_at_startup

platforms:
  linux:
  macos:
  windows:

topics:
  - launch-at-startup
  - launch-at-login
  - autostart
  - startup

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  nativeapi: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
